### ISSUE TITLE
Screenshots seem to not work anymore on wayland

### ISSUE THREAD

**Issue by artiommocrenco** [yurikoles-aur/upwork#4]
"switch to xorg" is now the official suggestion which is shown inside the app.

If a workaround is found, it would be great to incorporate it into the package, so that if wayland usage is detected, the workaround is utilized.

Otherwise its unusable for wayland people and wayland is the successor to xorg, it means that it is a popular choice for modern OS users.

![image](https://github.com/yurikoles-aur/upwork/assets/28516476/6b88bf67-d685-4bd8-9d4d-10458051114b)

**Comment by yurikoles** [comment]
Nothing is to be fixed in AUR, which is _downstream_.
